networks:
  web:
    external: true

services:
  quartz:
    build: .
    container_name: quartz
    restart: unless-stopped
    volumes:
      - "${PATH_TO_CONTENT}:/usr/src/app/content"
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.quartz.rule=Host(`blog.remigerme.xyz`)
      # https configuration
      - traefik.http.routers.quartz.tls=true
      - traefik.http.routers.quartz.tls.certresolver=myresolver
      # Connect the reverse proxy to the container port 8080
      - traefik.http.services.quartz.loadbalancer.server.port=8080
